#ifndef HUFF_MACROS
#define HUFF_MACROS


#define MAX_HUFF_ENCODING_LENGTH 16
#define TESTING 1

#ifndef TESTING 
#define SEGMENT_SIZE 16
#else
// #define SEGMENT_SIZE 512
#define SEGMENT_SIZE 4096
#endif

#define HUFF_TREE_MAX_NODE_COUNT 131071


#endif // HUFF_MACROS
